def GDP():
    gdp_2015 = {
        'PRT': 205.9,
        'GBR': 2860.0,
        'USA': 18120.0,
        'ESP': 1190.0,
        'IRL': 275.3,
        'FRA': 2420.0,
        'ROU': 178.6,
        'NOR': 387.1,
        'OMN': 67.03,
        'ARG': 552.88,
        'POL': 474.81,
        'DEU': 3380.0,
        'BEL': 494.72,
        'CHE': 664.93,
        'CN': 11060.0,
        'GRC': 195.68,
        'ITA': 1810.0,
        'NLD': 769.92,
        'DNK': 306.42,
        'RUS': 1330.0,
        'SWE': 493.49,
        'AUS': 1340.0,
        'EST': 23.67,
        'CZE': 190.49,
        'BRA': 1770.0,
        'FIN': 236.82,
        'MOZ': 12.83,
        'BWA': 16.05,
        'LUX': 60.75,
        'SVN': 45.73,
        'ALB': 11.9,
        'IND': 2180.0,
        'CHN': 11060.0,
        'MEX': 1140.0,
        'MAR': 109.1,
        'UKR': 90.46,
        'SMR': 1.69,
        'LVA': 27.36,
        'PRI': 103.11,
        'SRB': 36.29,
        'CHL': 240.21,
        'AUT': 382.49,
        'BLR': 55.21,
        'LTU': 42.08,
        'TUR': 1630.0,
        'ZAF': 314.75,
        'AGO': 102.29,
        'ISR': 299.53,
        'CYM': 4.0,
        'ZMB': 21.2,
        'CPV': 1.97,
        'ZWE': 16.63,
        'DZA': 166.74,
        'KOR': 1380.0,
        'CRI': 53.09,
        'HUN': 119.04,
        'ARE': 377.49,
        'TUN': 42.58,
        'JAM': 14.54,
        'HRV': 51.0,
        'HKG': 309.68,
        'IRN': 416.15,
        'GEO': 14.34,
        'AND': 2.87,
        'GIB': 1.85,
        'URY': 53.12,
        'JEY': 6.32,
        'CAF': 1.77,
        'CYP': 21.44,
        'COL': 292.18,
        'GGY': 3.22,
        'KWT': 68.16,
        'NGA': 481.07,
        'MDV': 3.17,
        'VEN': 482.52,
        'SVK': 95.45,
        'FJI': 4.82,
        'KAZ': 184.43,
        'PAK': 270.79,
        'IDN': 861.93,
        'LBN': 49.08,
        'PHL': 291.97,
        'SEN': 15.86,
        'SYC': 1.48,
        'AZE': 53.72,
        'BHR': 32.26,
        'NZL': 171.16,
        'THA': 395.35,
        'DOM': 67.43,
        'MKD': 11.79,
        'MYS': 296.45,
        'ARM': 10.88,
        'JPN': 4389.47,
        'LKA': 79.01,
        'CUB': 80.18,
        'CMR': 32.54,
        'BIH': 19.78,
        'MUS': 13.97,
        'COM': 0.61,
        'SUR': 4.81,
        'UGA': 24.57,
        'BGR': 49.11,
        'CIV': 31.63,
        'JOR': 37.94,
        'SYR': 24.13,
        'SGP': 308.58,
        'BDI': 2.67,
        'SAU': 646.44,
        'VNM': 193.6,
        'PLW': 0.23,
        'QAT': 164.27,
        'EGY': 330.16,
        'PER': 192.99,
        'MLT': 11.46,
        'MWI': 6.69,
        'ECU': 100.68,
        'MDG': 10.53,
        'ISL': 17.8,
        'UZB': 66.41,
        'NPL': 21.59,
        'BHS': 9.36,
        'MAC': 50.42,
        'TGO': 4.76,
        'TWN': 530.65,
        'DJI': 1.47,
        'STP': 0.32,
        'KNA': 0.84,
        'ETH': 64.58,
        'IRQ': 225.82,
        'HND': 19.86,
        'RWA': 8.33,
        'KHM': 17.04,
        'MCO': 6.06,
        'BGD': 195.07,
        'IMN': 6.94,
        'TJK': 7.57,
        'NIC': 12.42,
        'BEN': 8.79,
        'VGB': 1.29,
        'TZA': 47.16,
        'GAB': 14.33,
        'GHA': 42.26,
        'TMP': 1.42,
        'GLP': 9.91,
        'KEN': 63.4,
        'LIE': 6.37,
        'GNB': 0.96,
        'MNE': 4.08,
        'UMI': 18120.0, #UMI:United States Minor Outlying Islands
        'MYT': 0.92,
        'FRO': 2.36,
        'MMR': 66.86,
        'PAN': 48.06,
        'BFA': 12.65,
        'LBY': 39.15,
        'MLI': 13.07,
        'NAM': 12.79,
        'BOL': 33.15,
        'PRY': 29.44,
        'BRB': 4.66,
        'ABW': 2.53,
        'AIA': 2860.0, #英国的海外领土
        'SLV': 25.69,
        'DMA': 0.51,
        'PYF': 6.36,
        'GUY': 3.02,
        'LCA': 1.61,
        'ATA': None, #南极洲，删掉
        'GTM': 65.37,
        'ASM': 0.65,
        'MRT': 5.81,
        'NCL': 11.47,
        'KIR': 0.16,
        'SDN': 117.37,
        'ATF': 2420.0, #法国海外领土
        'SLE': 4.18,
        'LAO': 12.29
    }
    return gdp_2015

def continent():
    country_continents = {
        'PRT': 'Europe',
        'GBR': 'Europe',
        'USA': 'North America',
        'ESP': 'Europe',
        'IRL': 'Europe',
        'FRA': 'Europe',
        'ROU': 'Europe',
        'NOR': 'Europe',
        'OMN': 'Asia',
        'ARG': 'South America',
        'POL': 'Europe',
        'DEU': 'Europe',
        'BEL': 'Europe',
        'CHE': 'Europe',
        'CN': 'Asia',
        'GRC': 'Europe',
        'ITA': 'Europe',
        'NLD': 'Europe',
        'DNK': 'Europe',
        'RUS': 'Europe',
        'SWE': 'Europe',
        'AUS': 'Australia',
        'EST': 'Europe',
        'CZE': 'Europe',
        'BRA': 'South America',
        'FIN': 'Europe',
        'MOZ': 'Africa',
        'BWA': 'Africa',
        'LUX': 'Europe',
        'SVN': 'Europe',
        'ALB': 'Europe',
        'IND': 'Asia',
        'CHN': 'Asia',
        'MEX': 'North America',
        'MAR': 'Africa',
        'UKR': 'Europe',
        'SMR': 'Europe',
        'LVA': 'Europe',
        'PRI': 'North America',
        'SRB': 'Europe',
        'CHL': 'South America',
        'AUT': 'Europe',
        'BLR': 'Europe',
        'LTU': 'Europe',
        'TUR': 'Europe',
        'ZAF': 'Africa',
        'AGO': 'Africa',
        'ISR': 'Asia',
        'CYM': 'North America',
        'ZMB': 'Africa',
        'CPV': 'Africa',
        'ZWE': 'Africa',
        'DZA': 'Africa',
        'KOR': 'Asia',
        'CRI': 'North America',
        'HUN': 'Europe',
        'ARE': 'Asia',
        'TUN': 'Africa',
        'JAM': 'North America',
        'HRV': 'Europe',
        'HKG': 'Asia',
        'IRN': 'Asia',
        'GEO': 'Asia',
        'AND': 'Europe',
        'GIB': 'Europe',
        'URY': 'South America',
        'JEY': 'Europe',
        'CAF': 'Africa',
        'CYP': 'Europe',
        'COL': 'South America',
        'GGY': 'Europe',
        'KWT': 'Asia',
        'NGA': 'Africa',
        'MDV': 'Asia',
        'VEN': 'South America',
        'SVK': 'Europe',
        'FJI': 'Oceania',
        'KAZ': 'Asia',
        'PAK': 'Asia',
        'IDN': 'Asia',
        'LBN': 'Asia',
        'PHL': 'Asia',
        'SEN': 'Africa',
        'SYC': 'Africa',
        'AZE': 'Asia',
        'BHR': 'Asia',
        'NZL': 'Australia',
        'THA': 'Asia',
        'DOM': 'North America',
        'MKD': 'Europe',
        'MYS': 'Asia',
        'ARM': 'Asia',
        'JPN': 'Asia',
        'LKA': 'Asia',
        'CUB': 'North America',
        'CMR': 'Africa',
        'BIH': 'Europe',
        'MUS': 'Africa',
        'COM': 'Africa',
        'SUR': 'South America',
        'UGA': 'Africa',
        'BGR': 'Europe',
        'CIV': 'Africa',
        'JOR': 'Asia',
        'SYR': 'Asia',
        'SGP': 'Asia',
        'BDI': 'Africa',
        'SAU': 'Asia',
        'VNM': 'Asia',
        'PLW': 'Oceania',
        'QAT': 'Asia',
        'EGY': 'Africa',
        'PER': 'South America',
        'MLT': 'Europe',
        'MWI': 'Africa',
        'ECU': 'South America',
        'MDG': 'Africa',
        'ISL': 'Europe',
        'UZB': 'Asia',
        'NPL': 'Asia',
        'BHS': 'North America',
        'MAC': 'Asia',
        'TGO': 'Africa',
        'TWN': 'Asia',
        'DJI': 'Africa',
        'STP': 'Africa',
        'KNA': 'North America',
        'ETH': 'Africa',
        'IRQ': 'Asia',
        'HND': 'North America',
        'RWA': 'Africa',
        'KHM': 'Asia',
        'MCO': 'Europe',
        'BGD': 'Asia',
        'IMN': 'Europe',
        'TJK': 'Asia',
        'NIC': 'North America',
        'BEN': 'Africa',
        'VGB': 'North America',
        'TZA': 'Africa',
        'GAB': 'Africa',
        'GHA': 'Africa',
        'TMP': 'Asia',
        'GLP': 'North America',
        'KEN': 'Africa',
        'LIE': 'Europe',
        'GNB': 'Africa',
        'MNE': 'Europe',
        'UMI': 'North America',
        'MYT': 'Africa',
        'FRO': 'Europe',
        'MMR': 'Asia',
        'PAN': 'North America',
        'BFA': 'Africa',
        'LBY': 'Africa',
        'MLI': 'Africa',
        'NAM': 'Africa',
        'BOL': 'South America',
        'PRY': 'South America',
        'BRB': 'North America',
        'ABW': 'North America',
        'AIA': 'North America',
        'SLV': 'North America',
        'DMA': 'North America',
        'PYF': 'Oceania',
        'GUY': 'South America',
        'LCA': 'North America',
        'ATA': 'Antarctica',
        'GTM': 'North America',
        'ASM': 'Oceania',
        'MRT': 'Africa',
        'NCL': 'Oceania',
        'KIR': 'Oceania',
        'SDN': 'Africa',
        'ATF': 'Antarctica',
        'SLE': 'Africa',
        'LAO': 'Asia',
    }
    return country_continents

def full_name():
    country_full_names = {
        'PRT': 'Portugal',
        'GBR': 'United Kingdom',
        'USA': 'United States of America',
        'ESP': 'Spain',
        'IRL': 'Ireland',
        'FRA': 'France',
        'ROU': 'Romania',
        'NOR': 'Norway',
        'OMN': 'Oman',
        'ARG': 'Argentina',
        'POL': 'Poland',
        'DEU': 'Germany',
        'BEL': 'Belgium',
        'CHE': 'Switzerland',
        'CN': 'China',
        'GRC': 'Greece',
        'ITA': 'Italy',
        'NLD': 'Netherlands',
        'DNK': 'Denmark',
        'RUS': 'Russia',
        'SWE': 'Sweden',
        'AUS': 'Australia',
        'EST': 'Estonia',
        'CZE': 'Czech Republic',
        'BRA': 'Brazil',
        'FIN': 'Finland',
        'MOZ': 'Mozambique',
        'BWA': 'Botswana',
        'LUX': 'Luxembourg',
        'SVN': 'Slovenia',
        'ALB': 'Albania',
        'IND': 'India',
        'CHN': 'China',
        'MEX': 'Mexico',
        'MAR': 'Morocco',
        'UKR': 'Ukraine',
        'SMR': 'San Marino',
        'LVA': 'Latvia',
        'PRI': 'Puerto Rico',
        'SRB': 'Serbia',
        'CHL': 'Chile',
        'AUT': 'Austria',
        'BLR': 'Belarus',
        'LTU': 'Lithuania',
        'TUR': 'Turkey',
        'ZAF': 'South Africa',
        'AGO': 'Angola',
        'ISR': 'Israel',
        'CYM': 'Cayman Islands',
        'ZMB': 'Zambia',
        'CPV': 'Cape Verde',
        'ZWE': 'Zimbabwe',
        'DZA': 'Algeria',
        'KOR': 'South Korea',
        'CRI': 'Costa Rica',
        'HUN': 'Hungary',
        'ARE': 'United Arab Emirates',
        'TUN': 'Tunisia',
        'JAM': 'Jamaica',
        'HRV': 'Croatia',
        'HKG': 'Hong Kong',
        'IRN': 'Iran',
        'GEO': 'Georgia',
        'AND': 'Andorra',
        'GIB': 'Gibraltar',
        'URY': 'Uruguay',
        'JEY': 'Jersey',
        'CAF': 'Central African Republic',
        'CYP': 'Cyprus',
        'COL': 'Colombia',
        'GGY': 'Guernsey',
        'KWT': 'Kuwait',
        'NGA': 'Nigeria',
        'MDV': 'Maldives',
        'VEN': 'Venezuela',
        'SVK': 'Slovakia',
        'FJI': 'Fiji',
        'KAZ': 'Kazakhstan',
        'PAK': 'Pakistan',
        'IDN': 'Indonesia',
        'LBN': 'Lebanon',
        'PHL': 'Philippines',
        'SEN': 'Senegal',
        'SYC': 'Seychelles',
        'AZE': 'Azerbaijan',
        'BHR': 'Bahrain',
        'NZL': 'New Zealand',
        'THA': 'Thailand',
        'DOM': 'Dominican Republic',
        'MKD': 'North Macedonia',
        'MYS': 'Malaysia',
        'ARM': 'Armenia',
        'JPN': 'Japan',
        'LKA': 'Sri Lanka',
        'CUB': 'Cuba',
        'CMR': 'Cameroon',
        'BIH': 'Bosnia and Herzegovina',
        'MUS': 'Mauritius',
        'COM': 'Comoros',
        'SUR': 'Suriname',
        'UGA': 'Uganda',
        'BGR': 'Bulgaria',
        'CIV': 'Ivory Coast',
        'JOR': 'Jordan',
        'SYR': 'Syria',
        'SGP': 'Singapore',
        'BDI': 'Burundi',
        'SAU': 'Saudi Arabia',
        'VNM': 'Vietnam',
        'PLW': 'Palau',
        'QAT': 'Qatar',
        'EGY': 'Egypt',
        'PER': 'Peru',
        'MLT': 'Malta',
        'MWI': 'Malawi',
        'ECU': 'Ecuador',
        'MDG': 'Madagascar',
        'ISL': 'Iceland',
        'UZB': 'Uzbekistan',
        'NPL': 'Nepal',
        'BHS': 'Bahamas',
        'MAC': 'Macau',
        'TGO': 'Togo',
        'TWN': 'Taiwan',
        'DJI': 'Djibouti',
        'STP': 'São Tomé and Príncipe',
        'KNA': 'Saint Kitts and Nevis',
        'ETH': 'Ethiopia',
        'IRQ': 'Iraq',
        'HND': 'Honduras',
        'RWA': 'Rwanda',
        'KHM': 'Cambodia',
        'MCO': 'Monaco',
        'BGD': 'Bangladesh',
        'IMN': 'Isle of Man',
        'TJK': 'Tajikistan',
        'NIC': 'Nicaragua',
        'BEN': 'Benin',
        'VGB': 'British Virgin Islands',
        'TZA': 'Tanzania',
        'GAB': 'Gabon',
        'GHA': 'Ghana',
        'TMP': 'East Timor',
        'GLP': 'Guadeloupe',
        'KEN': 'Kenya',
        'LIE': 'Liechtenstein',
        'GNB': 'Guinea-Bissau',
        'MNE': 'Montenegro',
        'UMI': 'United States Minor Outlying Islands',
        'MYT': 'Mayotte',
        'FRO': 'Faroe Islands',
        'MMR': 'Myanmar',
        'PAN': 'Panama',
        'BFA': 'Burkina Faso',
        'LBY': 'Libya',
        'MLI': 'Mali',
        'NAM': 'Namibia',
        'BOL': 'Bolivia',
        'PRY': 'Paraguay',
        'BRB': 'Barbados',
        'ABW': 'Aruba',
        'AIA': 'Anguilla',
        'SLV': 'El Salvador',
        'DMA': 'Dominica',
        'PYF': 'French Polynesia',
        'GUY': 'Guyana',
        'LCA': 'Saint Lucia',
        'ATA': 'Antarctica',
        'GTM': 'Guatemala',
        'ASM': 'American Samoa',
        'MRT': 'Mauritania',
        'NCL': 'New Caledonia',
        'KIR': 'Kiribati',
        'SDN': 'Sudan',
        'ATF': 'French Southern Territories',
        'SLE': 'Sierra Leone',
        'LAO': 'Laos'
    }

    return country_full_names
